server:
  port: ${APP_PORT:8081}
  error:
    include-stacktrace: never
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_PG_HOST:localhost}:${DB_PG_PORT:5432}/${DB_PG_BASE:cat-purchase-service-db}?prepareThreshold=0
    username: ${DB_PG_USR_RW:postgres}
    password: ${DB_PG_PWD_RW:postgres}
  liquibase:
    enabled: false
rabbitmq:
  main:
    addresses: ${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}
    rabbit-host: ${RABBITMQ_VIRTUAL_HOST:vhost}
    enable: true
    password: ${RABBITMQ_PWD:guest}
    username: ${RABBITMQ_USR:guest}